### PR TITLE
Add ForkDigest filter

### PR DESCRIPTION
**Pull request by migalabs**
## Description

We ran an instance of the Nodewatch eth2-crawler for 24 hours (latest commit in the master branch [c161d309fcbf7cd4455c736e089def94b3919463](https://github.com/ChainSafe/eth2-crawler/commit/c161d309fcbf7cd4455c736e089def94b3919463)), and looked at the ForkDigest exposed by each peer. We noticed that only 83.1% of them correspond to the Altair mainnet, 2.5% correspond to Phase 0 (before Altair) and 14.4% to other testnets (See figure below). 

We are not aware of the purpose of the Nodewatch eth2-crawler and the collected data. We have not been able to find any documentation about the networks it operates on. Our conclusion is that, if the purpose of the crawler is to show all the peers participating in any of the Eth2 networks (including testnets), then this information should be explicitly mentioned in the website/dashboard, as anyone who reads it could think that it only applies to the Eth2 mainnet (Altair). However, if the purpose of your crawler is to gather data from the peers connected just to the Eth2 mainnet (Altair fork), then the filter proposed in this PR should be applied. 

Please note that the filter by client version that you implemented in your commit of October 22nd [c63e61b1940b2c56542926597744bed21e024e74](https://github.com/ChainSafe/eth2-crawler/commit/c63e61b1940b2c56542926597744bed21e024e74#diff-e0a4909f568588675db7c5cfb3aa4175267381ba017bc73e85f980bd3ed715ff) is not enough, as there could be nodes with an updated client version that is compatible with the new fork (Altair), but the node is not necessarily participating in the Eth2 mainnet, but could be connected to other testnet (e.g., prater).

image

## Changes

- Adding condition to check the ForkDigest before storing Peer in the database
- Only Peers with the defined ForkDigest will be stored

#### Closes: #?
There are no issues related to this Pull Request

### CODE REVIEW

**Comment by infosecual** [comment]
The EF is happy with supporting mainnet only. If we can spin up separate instances to monitor testnets when needed.

**Review by infosecual — COMMENTED** [review]
LGTM. Will defer to NodeWatch team to approve.

**Comment by dhyaniarun1993** [comment]
Thanks @migalabs. We are looking into this.

**Review by sadiq1971 — APPROVED** [review]

**Review by dhyaniarun1993 — CHANGES_REQUESTED** [review]
@migalabs Please sign the contributors license

**Comment by migalabs** [comment]
> @migalabs Please sign the contributors license

It should be already signed, let us know if there are further steps to follow

**Comment by wemeetagain** [comment]
IMO it might be nice for the crawler to grab all eth2 peers, and only filter afterwards in the database queries.

I'd argue that storing / querying eth2 peers across all testnets is a small additional overhead, and that it gives you flexibility to perform possibly interesting queries down the line.

**Comment by dhyaniarun1993** [comment]
> > @migalabs Please sign the contributors license
> 
> It should be already signed, let us know if there are further steps to follow

@migalabs Please sign the contributors license. It's still pending

**Comment by sadiq1971** [comment]
Done it here https://github.com/ChainSafe/nodewatch-api/pull/206

**Pull request closed without merging**
